name: 'Grasshopper componentizer'
description: 'Create GHUser components from Python source code'
inputs:
  source:
    description: 'Source directory where code for all components is stored'
    required: true
  target:
    description: 'Target directory for ghuser files'
    required: true
  prefix:
    description: 'Add this prefix to the name of each generated component'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
      command="ipy ipy ${{ github.action_path }}/componentize.py ${{ inputs.source }} ${{ inputs.target }} --ghio ./lib"
      prefix="${{ inputs.prefix }}"      
      if [ -n "$prefix" ]; then
        command="$command --prefix $prefix"
      fi
    - run: nuget install Grasshopper -OutputDirectory ./lib -source https://api.nuget.org/v3/index.json
      shell: pwsh
    - run: $command
      shell: pwsh
branding:
  icon: 'box'
  color: 'orange'
