name: build

on: [push]

jobs:
  build_ipy_ghuser_components:
    name: windows-cpython
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5

      - name: Run
        uses: ./
        with:
          source: examples/ipy
          target: build/ipy

      - uses: actions/upload-artifact@v2
        with:
          name: ipy_ghuser-components
          path: build/ipy

  build_cpy_ghuser_components:
    name: windows-cpython
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5

      - name: Run
        uses: ./
        with:
          source: examples/cpy
          target: build/cpy
          interpreter: cpython

      - uses: actions/upload-artifact@v2
        with:
          name: cpy_ghuser-components
          path: build/cpy