name: build

on: [push]

jobs:
  build_ghuser_components:  # TODO: change this for windows-ironpython (it can be another workflow)
    name: windows-cpython  # TODO: change this for windows-ironpython
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5

      - name: Run
        uses: ./
        with:
          source: examples/ipy
          target: build

      - uses: actions/upload-artifact@v2
        with:
          name: ghuser-components
          path: build